[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --strict-markers
    --strict-config
    --html=reports/report.html
    --self-contained-html
    -n auto
markers =
    smoke: Smoke tests
    regression: Regression tests
    #performance: Performance tests
    #stable: marks stable performance tests
    performance: mark as performance tests
    stable: mark as stable performance tests

